global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'vector'
    static_configs:
      - targets: ['vector:9090']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
